### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by jmangelson** [mujx/hakatime#14]
I am very interested in hakatime, however I am having trouble configuring it to run with nginx alongside multiple other services. 
Ex: <my-url>/hakatime

Do you by chance have a sample nginx configuration file for hakatime?

**Comment by mujx** [comment]
What is the problem? Do you have any errors in the logs?

It might be a CORS issue. Do you have the correct value for the environment variable `HAKA_CORS_URL`? It should be something like `https://my-domain.com` which should be the URL you're using to access the service.

**Comment by jmangelson** [comment]
Yes, I can get that for you.

Could you point me to where I should get the logs?



On Dec 15, 2020 6:15 PM, mujx <notifications@github.com> wrote:

What is the problem? Do you have any errors in the logs?

It might be a CORS issue. Do you have the correct value for the environment variable HAKA_CORS_URL? It should be something like https://my-domain.com which should be the URL you're using to access the service.

**Comment by mujx** [comment]
`docker logs <service-name>` should do it. 

In any case putting hakatime behind a proxy doesn't require something special. Just make sure the CORS variable is set correctly.

**Comment by mujx** [comment]
@jmangelson Any updates on this?

**Comment by jmangelson** [comment]
I'm still having problems getting nginx to find the dashboard web files. It gives a "file not found" error when I go to the url that nginx forwards to the dashboard docker container.

However, I am sure the hakatime image is running correctly since I can access it via the url with the host port included.

For some reason hakatime is unable to find the index.html file in /app/bin/dashboard

Joshua Mangelson, Ph.D
Assistant Professor
Electrical and Computer Engineering
Brigham Young University

On Dec 23, 2020 4:59 AM, mujx <notifications@github.com> wrote:

@jmangelson<https://github.com/jmangelson> Any updates on this?

**Comment by mujx** [comment]
I can give some more concrete feedback if you share the relevant parts of your nginx config and how you run the hakatime container.

I'm using haproxy for the demo website but it shouldn't be much of a difference for the nginx case.

Here is what an nginx.conf might look like
```nginx
server {
    listen 80;
    location / {
        proxy_pass http://127.0.0.1:8080; # Assuming the hakatime service is listening on 127.0.0.1:8080
    }
}
```
You should pass the `HAKA_CORS_URL` the domain that you'll use to access the service. 

So if your domain is `hakatime.example.com` the variable should be `HAKA_CORS_URL: https://hakatime.example.com`

> For some reason hakatime is unable to find the index.html file in /app/bin/dashboard

If you're using the upstream image can you verify that the files exist in the image by running the following

```sh
docker exec -it hakatime ls -l /app/bin/dashboard
```

**Comment by hea3ven** [comment]
Hello, I think I'm having the same issue that jmangelson is having. What I want to do is have hakatime running at http://my-domain.com/private/hakatime. To do this I've set the `HAKA_CORS_URL` to `http://my-domain.com/private/hakatime`, but hakatime would fail with a body "" probably cause it's not expecting the `/private/hakatime` prefix. If in my nginx I rewrite the url to remove the `/private/hakatime` part, I am able to load the login page, but it fails when trying to login with the message `hakatime:72 POST http://my-domain.com/auth/login 404 (Not Found)` in the javascript console because it's not using `http://my-domain.com/private/hakatime/auth/login`.

I'm guessing this use case is not implemented.

**Comment by mujx** [comment]
@hea3ven Yes, that would be something extra to be implemented. The ability to dynamic prefix all the paths.

I'll try to implement something like that in the coming days, but in the meantime you might be able to solve your issue by using a subdomain (if you have that kind of control). So you'll have your service exposed like `http://hakatime.my-domain.com`.

**Comment by jmangelson** [comment]
This is the same problem I'm having, but I don't have access to create a sub domain.

If you were able to implement that functionality that would be very helpful.

Josh

On Jan 14, 2021 3:24 AM, mujx <notifications@github.com> wrote:

@hea3ven<https://github.com/hea3ven> Yes, that would be something extra to be implemented. The ability to dynamic prefix all the paths.

I'll try to implement something like that in the coming days, but in the meantime you might be able to solve your issue by using a subdomain (if you have that kind of control). So you'll have your service exposed like http://hakatime.my-domain.com.

**Comment by mujx** [comment]
@jmangelson @hea3ven I've pushed some changes and now it's possible to use hakatime in your setup.

You would need something like the following in the nginx.conf to overwrite some paths that come from third party css.

```conf
server {
  listen 9999;

  location /private/hakatime {
    rewrite /private/hakatime/(.*) /$1 break;

    sub_filter 'href="/icons/'  'href="/private/hakatime/icons/';
    sub_filter 'href="/images/'  'href="/private/hakatime/images/';
    sub_filter 'url(/'  'url(/private/hakatime/';

    sub_filter_once off;

    proxy_pass http://hakatime:9090;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}

```

The `HAKA_CORS_URL` is renamed to `HAKA_BADGE_URL` and it's only related to the badge generation. You'll need to set `HAKA_API_PREFIX: '/private/hakatime'` so that the auth cookies are set properly. 

Please test it out and let me know if you have any issues.

**Comment by mujx** [comment]
Closing this as resolved. Feel free to re-open if you encounter any issues with the setup.
