### ISSUE TITLE
import data from wakatime timeout

### ISSUE THREAD

**Issue by WankkoRee** [mujx/hakatime#43]
I am in Hong Kong. If i use `api.wakatime.com`, it will time out. But if I use `wakatime.com`, then everything works fine. 

![image](https://user-images.githubusercontent.com/21287731/131523987-f00ff675-df1f-4b13-a3bc-c76ccf7f5f7d.png)

So can there be an option in `docker-compose-deploy.yml` for setting importing from which domain? Just like `HAKA_WAKATIME_HOST: "wakatime.com"`

**Comment by mujx** [comment]
Are you sure the problem is your location and not the amount of data you're expecting? Maybe the server is slow to respond and a second try will most likely fetch your data.

You can check that both `wakatime.com` & `api.wakatime.com` are in California, USA so the latency should be the same.  Or is `api.wakatime.com` blocked in Hong Kong?

**Comment by WankkoRee** [comment]
Look at the screenshot I uploaded earlier. I did not set user credentials such as cookies and tokens. I just send an anonymous request. But the response time of the two domains is quite different.

**Comment by mujx** [comment]
You're right. It seems like the `api.wakatime.com` is only redirecting to `wakatime.com/api` on HTTP . This will work `curl http://api.wakatime.com/v1/users/current/heartbeats`, but it returns HTML instead of JSON.  Removing the `/api` path with HTTPS like`curl https://api.wakatime.com/v1/users/current/heartbeats` also works but still no JSON.

I'll provide a variable to control this endpoint. Thanks for the suggestion.

**Comment by mujx** [comment]
@WankkoRee I pushed a quick fix that uses the correct endpoint (`wakatime.com`). In the future this will be configurable.

**Comment by WankkoRee** [comment]
Thank you for your timely fix. I tried to import again and everything was working.
