### ISSUE TITLE
Good first issues

### ISSUE THREAD

**Issue by daniel-naegele** [mujx/hakatime#77]
Hey,

first of all thank you very much for this nice piece of software.
I wanted to get started with real Haskell programming (had a minor course about it in college) and thought about contributing to this package. Are there any issues/features/bugs which would be a good first issue? Maybe you could outline in some tickets the needed steps to complete it to get started with working on Hakatime.

**Comment by mujx** [comment]
Hi @daniel-naegele , thanks a lot for your interest in hakatime! I've labeled some of the tasks as `good-first-issue` that I think would help you to get started with Haskell.

Although I think most of those current open issues are relatively easy/straight-forward to implement, some of them require also some frontend work. That's why I didn't label all of them, but feel free to pick any task and only handle the Haskell part.

**Comment by mujx** [comment]
Closing this now that are some open good first-timer issues.
